In [1]:
import numpy as np

### Creating a vector ###

In [2]:
vector = np.array([1,2,3,4,5])

### Creating a matirx ###

In [10]:
matrix = np.array([[1,2,3],
                  [2,3,4],
                  [3,4,5]])

In [11]:
matrix.T

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

### Selecting an element ###

In [12]:
vector[1]
matrix[1,2]

4

### Create a tensor ###

In [19]:
tensor = np.array([
                    [[[1,1],[1,1]],[[2,2],[2,2]]],
                    [[[3,3],[3,3]],[[4,4],[4,3]]]
                 ])
tensor

array([[[[1, 1],
         [1, 1]],

        [[2, 2],
         [2, 2]]],


       [[[3, 3],
         [3, 3]],

        [[4, 4],
         [4, 3]]]])

### Selecting an element from a tensor ###

In [21]:
tensor[0,0,0]

array([1, 1])

![tensors](tensors.png)

### Reshaping a Matrix ###

In [29]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])

In [31]:
matrix.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

### Invert a matrix 
Only a square matrix can be inverted

In [34]:
matrix = np.array(
    [[1,3],
    [2,4]]
)

In [36]:
np.linalg.inv(matrix)

array([[-2. ,  1.5],
       [ 1. , -0.5]])

### Getting diagonal of a matrix

In [37]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [38]:
matrix.diagonal()

array([1, 5, 9])

#### Trace of a matrix
Trace of a matrix is the sum of elements of a diagonal in a matrix

In [40]:
matrix.diagonal().sum()

15

### Flatten a matrix

In [41]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### Rank of a matrix
The maximum number of linearly independent vectors in a matrix is equal to the number of non-zero rows in its row echelon matrix. Therefore, to find the rank of a matrix, we simply transform the matrix to its row echelon form and count the number of non-zero rows.

In [42]:
np.linalg.matrix_rank(matrix)

2

### Finding Min and Max in a matrix

In [46]:
np.max(matrix)

9

In [47]:
np.min(matrix)

1

### Finding Max and Min in a each rows and columns

In [48]:
#in each column
np.max(matrix,axis=0)

array([7, 8, 9])

In [50]:
# in each row
np.max(matrix,axis=1)

array([3, 6, 9])

### Describe an Array

In [52]:
matrix.shape

(3, 3)

In [54]:
matrix.size

9

In [55]:
matrix.ndim

2

### Create a vector
A vector is of the form a```i``` + b```j``` + c```k```

Create a vector as a row

In [56]:
vector_row = np.array([1,2,3])

Create a vector as a column

In [57]:
vector_col = np.array([
    [1],
    [2],
    [3]
])

### Create a sprase matrix

In [60]:
from scipy import sparse

In [59]:
matrix = np.array([
    [0,0],
    [0,1],
    [3,0]
])

In [61]:
#createa compressed sparse row (CSR) matrix
matrix_sparse = sparse.csr_matrix(matrix)

In [62]:
matrix_sparse

<3x2 sparse matrix of type '<class 'numpy.int32'>'
	with 2 stored elements in Compressed Sparse Row format>

### Converting a Dictionary to a matrix

In [64]:
from sklearn.feature_extraction import DictVectorizer

In [66]:
data_dict = [
            {'Red':2, 'Blue':4},
            {'Red':4, 'Blue':3},
            {'Red':1, 'Yellow':2},
            {'Red':2, 'Yellow':2}
]

In [67]:
dictvectorizer = DictVectorizer(sparse=False)
features = dictvectorizer.fit_transform(data_dict)
features

array([[4., 2., 0.],
       [3., 4., 0.],
       [0., 1., 2.],
       [0., 2., 2.]])

In [68]:
#View column names
dictvectorizer.get_feature_names()

['Blue', 'Red', 'Yellow']

### Determinant of a matrix

In [69]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [70]:
np.linalg.det(matrix)

-9.51619735392994e-16

### Calculating Average(Mean) , Variance and Standard Deviation

In [71]:
np.mean(matrix)

5.0

In [72]:
np.var(matrix)

6.666666666666667

In [73]:
np.std(matrix)

2.581988897471611

### Calculate Dot Product of 2 Vectors (Not arrays!)

In [74]:
vector_a = np.array([1,2,3])
vector_b = np.array([4,5,6])

Method 1

In [75]:
np.dot(vector_a,vector_b)

32

Method 2

In [76]:
vector_a @ vector_b

32

### Apply Operations to elements ***

In [78]:
#create a function that adds 100 to somwthing
add_100 = lambda i:i + 100

#Create a vectorized function
vectorized_add_100 = np.vectorize(add_100)

In [79]:
# apply above fumction to all elements in a matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

### Adding and Subtracting Matrices

In [80]:
matrix_a = np.array([[1, 1, 1],
                     [1, 1, 1],
                     [1, 1, 2]])

matrix_b = np.array([[1, 3, 1],
                     [1, 3, 1],
                     [1, 3, 8]])

In [81]:
np.add(matrix_a,matrix_b)

array([[ 2,  4,  2],
       [ 2,  4,  2],
       [ 2,  4, 10]])

In [82]:
np.subtract(matrix_a,matrix_b)

array([[ 0, -2,  0],
       [ 0, -2,  0],
       [ 0, -2, -6]])